# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160203_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rating',
            field=models.CharField(default=0, max_length=20, verbose_name='Rating'),
        ),
    ]
