# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160204_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='family_id',
            field=models.ForeignKey(default='1111', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Family'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=20, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, default='exp', max_length=20, verbose_name='Type'),
        ),
    ]
