# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160204_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='exp', max_length=20, verbose_name='Type'),
        ),
    ]
