# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160204_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='exp', max_length=20, verbose_name='Type'),
        ),
    ]
