# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160209_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='category_id',
        ),
    ]
