# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160212_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='family_id',
        ),
        migrations.AddField(
            model_name='family',
            name='pin',
            field=models.CharField(default=9999, max_length=4, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.IntegerField(default=111111, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
