# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160215_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='family',
            name='pin',
            field=models.CharField(default=0, max_length=4, verbose_name='PIN'),
        ),
    ]
