# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160215_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='family_id',
            field=models.ForeignKey(blank=True, default=111111, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Family'),
        ),
    ]
