# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_transaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='creator',
            field=models.CharField(blank=True, max_length=20, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='family',
            name='pin',
            field=models.IntegerField(default=0, verbose_name='PIN'),
        ),
    ]
