# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160216_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('e', 'Expense'), ('i', 'Income')], default='e', max_length=1, verbose_name='Type'),
        ),
    ]
