# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160216_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-id',), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_dec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Amount_dec'),
            preserve_default=False,
        ),
    ]
