# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_category_icon_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='family_id',
            field=models.ForeignKey(default=111111, on_delete=django.db.models.deletion.CASCADE, to='core.Family'),
        ),
    ]
